name: Testing...

on:
  push:
    branches:
      - init-branch

jobs:
  TEST:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install && npm install @actions/github --save

    - name: Build action
      run: npm run build 

    - name: Run reusable action
      id: run1
      uses: P4dr4/ActionsExp@init-branch
